// Data for multiple tabs 
let choiceData = {
  Fun: [
    "Board games revival",
    "Comedy trends",
    "Amusement parks",
    "Escape rooms",
    "Street performances",
    "Online challenges",
    "Festivals impact",
    "Crafting movement",
    "Social gaming",
    "Virtual reality",
  ],
  Education: [
    "Gamified learning",
    "Education systems",
    "Bilingual benefits",
    "Standardized testing",
    "Arts in schools",
    "Tech bootcamps",
    "Homeschooling dynamics",
    "Mentorship importance",
    "Educational equity",
    "Mobile learning",
  ],
  Sports: [
    "Sports medicine",
    "Team sociology",
    "Olympic economics",
    "Gender parity",
    "Fandom psychology",
    "Extreme sports",
    "Sports business",
    "Youth athletics",
    "Data analytics",
    "Doping ethics",
  ],
  News: [
    "Citizen journalism",
    "Whistleblower influence",
    "Fake news",
    "Print media survival",
    "Social media news",
    "Cybersecurity news",
    "Democratic media",
    "News deserts",
    "News economics",
    "Broadcast evolution",
  ],
  Investment: [
    "Robo-advising",
    "Geopolitical impacts",
    "Index funds",
    "Real estate trends",
    "Startup investing",
    "Social trading",
    "Tax strategies",
    "Emerging markets",
    "Financial literacy",
    "Pension futures",
  ],
  Facts: [
    "Animal oddities",
    "Everyday science",
    "Historical obscurities",
    "Science myths",
    "Human body facts",
    "Oceanic discoveries",
    "Space exploration",
    "Ancient tech",
    "World laws",
    "Bizarre news",
  ],
};
export { choiceData };
