import { Inter } from "next/font/google";
import Header from "@/components/header/Header";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import ThemeRegistry from '@/utils/ThemeRegistry'
import { AppBar, Box, CssBaseline, Toolbar } from "@mui/material";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <ThemeRegistry options={{ key: 'theme-t' }}>
          
          <Box display="flex" flexDirection="column" minHeight="100vh">
            <CssBaseline />

            {/* Top App Bar. Set the possition 'relative' if don't want's the sticky header */}
            <AppBar position="sticky">
              <Header key="header" />
            </AppBar>

            {/* Page Content */}
            <Box flexGrow={1} p={2} sx={{
              padding: 0
            }}>
              {children}
            </Box>

            {/* Bottom App Bar */}
            <AppBar position="sticky" style={{ top: 'auto', bottom: 0 }}>
              <Footer key="footer" />
            </AppBar>
          </Box>

        </ThemeRegistry>

      </body>
    </html>
  );
}
